schema_version = "1.0.0"

id = "blentom"
version = "3.1.5"
name = "Blentom"
tagline = "Import of common electronic structure files"
maintainer = "Dominik Brandstetter <dominik.brandstetter@uni-graz.at>"
website = "https://github.com/brands-d/blentom/issues"
license = ["GPLv3"]
type = "add-on"
blender_version_min = "4.2.0"
platforms = ["windows-x64", "macos-arm64", "linux-x64"]

wheels = [
    "./wheels/ase-3.25.0-py3-none-any.whl",
    "./wheels/contourpy-1.3.2-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/contourpy-1.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/contourpy-1.3.2-cp311-cp311-win_amd64.whl",
    "./wheels/cycler-0.12.1-py3-none-any.whl",
    "./wheels/fonttools-4.57.0-cp311-cp311-macosx_10_9_universal2.whl",
    "./wheels/fonttools-4.57.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/fonttools-4.57.0-cp311-cp311-win_amd64.whl",
    "./wheels/kiwisolver-1.4.8-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/kiwisolver-1.4.8-cp311-cp311-win_amd64.whl",
    "./wheels/matplotlib-3.10.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/matplotlib-3.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/matplotlib-3.10.1-cp311-cp311-win_amd64.whl",
    "./wheels/packaging-25.0-py3-none-any.whl",
    "./wheels/pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pillow-11.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl",
    "./wheels/PyMCubes-0.1.6-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/PyMCubes-0.1.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/PyMCubes-0.1.6-cp311-cp311-win_amd64.whl",
    "./wheels/pyparsing-3.2.3-py3-none-any.whl",
    "./wheels/python_dateutil-2.9.0.post0-py2.py3-none-any.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-macosx_12_0_arm64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-win_amd64.whl",
    "./wheels/six-1.17.0-py2.py3-none-any.whl"
]

[permissions]
network = "Needed to download molecular orbitals from the database"
files = "Import of the atomic data"

[build]
paths_exclude_pattern = ["__pycache__/", "/.git/", "/*.zip"]