#! python3
import re
from pathlib import Path

VERSION_FILE = Path(".version")
version = VERSION_FILE.read_text().strip().split(".")
TARGET_FILES = [Path("blentom/blender_manifest.toml"), Path("Makefile")]
REGEXES = [
    {
        "find": r"^version = \"\d+\.\d+\.\d+",
        "replace": rf'version = "{version[0]}.{version[1]}.{version[2]}',
    },
    {
        "find": r"VERSION = \d+\.\d+\.\d+",
        "replace": rf"VERSION = {version[0]}.{version[1]}.{version[2]}",
    },
]

for file, regex in zip(TARGET_FILES, REGEXES):
    content = file.read_text()
    content = re.sub(regex["find"], regex["replace"], content, 1, re.MULTILINE)
    file.write_text(content)
